<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>Mixtape</PackageId>
        <Version>1.0.0</Version>
        <TargetFramework>net10.0</TargetFramework>
        <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
        <AssemblyName>Mixtape</AssemblyName>
        <RootNamespace>Mixtape</RootNamespace>
        <DebugType>embedded</DebugType>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="10.0.7" />
        <PackageReference Include="FluentValidation" Version="12.1.1" />
        <PackageReference Include="PowCapServer.Core" Version="2.0.1" />
        <PackageReference Include="Seq.Extensions.Logging" Version="9.0.0" />
        <PackageReference Include="SixLabors.ImageSharp.Web" Version="3.2.0" />
    </ItemGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Debug'">
        <PackageReference Include="ViteProxy" Version="1.3.0" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource LogicalName="mixtape/res/cap/cap.js" Include="..\modules\cap\widget\src\cap.min.js" />
      <EmbeddedResource LogicalName="mixtape/res/cap/cap.wasm" Include="..\modules\cap/wasm/src/browser/cap_wasm_bg.wasm" />
    </ItemGroup>

</Project>